create database Project;
use Project;
alter table students add unique(admission_no);
alter table students add unique(email_id);
alter table students add unique(mobile);
alter table students modify column admission_date varchar(255) not null;
alter table students modify column batch varchar(255) not null;
alter table students modify column branch varchar(255) not null;
alter table students modify column current_address varchar(255) not null;
alter table students modify column dob varchar(255) not null;
alter table students modify column email_id varchar(255) not null;
alter table students modify column first_name varchar(255) not null;
alter table students modify column gender varchar(255) not null;
alter table students modify column guardian_name varchar(255) not null;
alter table students modify column last_name varchar(255) not null;
alter table students modify column major varchar(255) not null;
alter table students modify column mobile varchar(255) not null;
alter table students modify column permanent_address varchar(255) not null;
desc students;
insert into students values(123,"2016-07-12",86859,82,"2016-2020","CSE","Hyderabad","1999-03-21","thomas@gmail.com","Thomas","Male","Shane","Mathew","BTech","3746792470","Hyderabad");
insert into students values(436,"2018-07-16",93586,87,"2018-2022","EEE","Chennai","2001-11-13","rosenta@gmail.com","Rosenta","Female","Marco","Patrick","BE","4857693845","Chennai");
select * from students;